Develop
Itopan1108/webapp2-renew pull request #1
Opened 2024-05-19 02:18 UTC by Itopan1108

@h-yokoyama-eiwa  @ma-miyagawa @esmtodoroki
cc @hyamakawa @esm-ksakai

ものすごく遅くなりましたが、
web開発２のプルリクレビュー（初回）がやっと出せます。
レビューのほど、よろしくお願いします。（お手柔らかに）

参考に、デプロイしたwebリンクを貼り付けます。（以下）
https://script.google.com/a/macros/esm.co.jp/s/AKfycbyVBOs-jWfunDvwSRurVOlm07fwFLwkn8TzL4Gy82p8C-nyyJ7KpjRJhIxvXs-8cz4/exec#/

今回のレビュー対象の部分は、カリキュラム上の以下スケジュールの黄色網掛けの部分です。
（スケジュールの日付については、先ほど坂井さんと話して、８月末に向けて引き直す予定です。お待ちください）
https://docs.google.com/spreadsheets/d/1_MSGglPpa7VorFsqNwv_FM0crQeWA-M5RVI0FDdTZ-8/edit#gid=1833026396

よろしくお願いします。

2024-05-20 07:00 UTC, esmtodoroki commented
ファイル分割については、ひとまず上手くいっているようですね。
SearchとListの部分が、それぞれ別ファイルの内容を読み込んで表示されていることを確認しました。

画面のほうなんですが、提示されている仕様に沿っていません。
今作られているものは、画面の「イメージ」をコピーしたものでしかなく、実際に表示されるべき内容はスキル面カリキュラムに書かれています。
「作るモノ」の部分です。そこをよく読んで、要求仕様に沿った項目を表示するようにしましょう。

それから、項目の右端が画面外に出てしまっていて、見ることが出来ませんでした。
私の社給PCの画面が小さいせいですが、小さい画面で表示すると一覧の画面も折り返して表示されるようにしてください。
参考として指定されている画面イメージのサイトを表示して、ブラウザーのウインドウを横方向に小さくしても、枠が小さくなりながら追随することを確認できるはずです。それと同じような感じで。

2024-05-20 10:50 UTC, ma-miyagawa commented
轟さんが指摘されていることと重複していないことで指摘を記載します。

タスクでは「Vue,Vuetifyを用いる」と記載されていますが、
一覧を表示させるために、Vuetify（Data tables）を使用せず、TABLEタグを使用しています。
後続のタスクでも一覧を表示させるためのタスクが存在しません。どのタイミングで実現させるのでしょうか？
今回のアプリケーションでは、最初に一覧を表示させる⇒検索機能をつけ⇒明細画面を表示させるという流れが
自然だと思うので、一覧の表示の機能を完璧にすることが最優先でないかと思います。

2024-05-20 11:00 UTC, h-yokoyama-eiwa requested changes
@Itopan1108 
まだ全部は見れていませんが、一旦指摘を投稿しておきます。
続きはまた時間を見つけて見ますが、もう一度仕様をちゃんと確認してください。
また、本来修正の要らない土台部分に修正が入っていますが、金融的な考えだとあまり好ましくないかと思います。
モダン界隈だとどうなのかわからないですけれど。

2024-05-20 11:00 UTC, h-yokoyama-eiwa commented on study_template/web_application_2/public/index.html
> +      >
< strong >タグの改行位置がおかしくなってますね。
< strong >←これが開始タグで　'</ strong >'←これが終了タグなので、「>」の前で改行すると見た目が変になります。
改行するのなら開始タグは「>」の後ろで、終了タグは「<」の前で改行してください。

ちなみにこのファイルは本来修正しなくても良いものかと思いますが、改行とか入れて見やすく（？）したってことですかね？

2024-05-20 11:00 UTC, h-yokoyama-eiwa commented on study_template/web_application_2/src/App.vue
> +    <v-app-bar app dark color="primary">
こちらも本来は修正不要かと思うのですが、index.htmlとは逆でなぜこちらは改行をなくしてしまったのでしょう？

2024-05-20 11:00 UTC, h-yokoyama-eiwa commented on study_template/web_application_2/src/components/TheForm.vue
> +    <v-card>
< v-card >のところのインデント幅だけ大きくないですか？
ここだけなら見難いとかはないですけど揃えた方が良いかと。

2024-05-20 11:00 UTC, h-yokoyama-eiwa commented on study_template/web_application_2/src/components/TheForm.vue
> +</template>
課題のアプリの見た目を作っているはずなのに仕様がガン無視されていますね。
『表示するデータは「タイトル」「ジャンル」「購入日」「購入者」のみとする』と書かれていますので仕様と全く異なっています。

2024-05-27 05:31 UTC, h-yokoyama-eiwa commented
全体的にインデント（字下げ）幅が揃っていないので、揃えましょう。
https://ics.media/entry/10234/

2024-06-24 08:51 UTC, Itopan1108 commented on study_template/web_application_2/src/components/TheForm.vue
> +    <v-card>
たしかに、4桁インデントが入っているところがありますね。
インデントは２桁づつの考えで、全体を見直しました。

2024-06-24 08:52 UTC, Itopan1108 commented on study_template/web_application_2/src/components/TheForm.vue
> +</template>
仕様の認識齟齬がありました。
轟さんから最初に同様の指摘をもらっているので、そちらで対応いたします。

2024-07-07 23:06 UTC, Itopan1108 commented
> ファイル分割については、ひとまず上手くいっているようですね。 SearchとListの部分が、それぞれ別ファイルの内容を読み込んで表示されていることを確認しました。
> 
> 画面のほうなんですが、提示されている仕様に沿っていません。 今作られているものは、画面の「イメージ」をコピーしたものでしかなく、実際に表示されるべき内容はスキル面カリキュラムに書かれています。 「作るモノ」の部分です。そこをよく読んで、要求仕様に沿った項目を表示するようにしましょう。
> 
> それから、項目の右端が画面外に出てしまっていて、見ることが出来ませんでした。 私の社給PCの画面が小さいせいですが、小さい画面で表示すると一覧の画面も折り返して表示されるようにしてください。 参考として指定されている画面イメージのサイトを表示して、ブラウザーのウインドウを横方向に小さくしても、枠が小さくなりながら追随することを確認できるはずです。それと同じような感じで。


伊藤です。2024/7/8
「作るモノ」を参照し、そちらをベースに作り変えてみました。ありがとうございます。
画面の伸縮にも、耐えうる形になりました。（  <v-container fluid>　の　fluid は　つけなくても挙動は変わらなかったので、取りました）　

2024-07-07 23:07 UTC, Itopan1108 commented on study_template/web_application_2/public/index.html
> +      >
@h-yokoyama-eiwa 
指摘修正しました。

2024-07-07 23:07 UTC, Itopan1108 commented on study_template/web_application_2/src/App.vue
> +    <v-app-bar app dark color="primary">
@h-yokoyama-eiwa
指摘修正しました。

2024-07-08 00:42 UTC, h-yokoyama-eiwa commented on study_template/web_application_2/public/index.html
> +      >
@Itopan1108 
これは元に戻す対応をした、ってことでいいんでしょうか？
この指摘のように対応が複数考えられる指摘を受けた場合は、どう対応したのか（必要ならなぜそうしたのか、も合わせて）記載してもらえるとレビューする側も楽なので次から意識してみてください。

で、元に戻す対応をしたという前提で話をすると、
<strong>We're sorry but CrewSMART doesn't work properly without JavaScript
で改行が入ってしまっていて元に戻し切れていないですね。
差分をちゃんと確認しましょう。

2024-07-08 00:46 UTC, h-yokoyama-eiwa commented on study_template/web_application_2/src/App.vue
> +    <v-app-bar app dark color="primary">
@Itopan1108 
上の指摘と同様に元に戻す対応をした、という前提で指摘しますが、
<v-app-bar　と　 app　の間に改行がないので元に戻し切れていないです。
これもちゃんと差分を確認すれば気づけるかと思います。

2024-07-08 00:50 UTC, h-yokoyama-eiwa commented on study_template/web_application_2/src/components/TheForm.vue
> +    <v-card>
修正が確認できました。

2024-07-08 00:59 UTC, h-yokoyama-eiwa commented on study_template/web_application_2/src/components/TheForm.vue
> +</template>
見た目が仕様に則したものになっていることを確認しました。

2024-07-08 03:52 UTC, h-yokoyama-eiwa commented
@Itopan1108 
いくつかコメント返しましたので確認してください。

2024-07-08 08:28 UTC, ma-miyagawa requested changes
@Itopan1108 

コメントを記載したので、対応をお願いします。
実装を変更した後のゴミがあったのでこの際片付けましょう

2024-07-08 08:28 UTC, ma-miyagawa commented on study_template/web_application_2/src/components/TheList.vue
> +<style scoped>
#btn4などのスタイルは不要になったので、削除してください

2024-07-08 08:28 UTC, ma-miyagawa commented on study_template/web_application_2/src/view/BookApp.vue
> +  <!--  <div class="wrap"> -->
削除コメントは、残さないでください。
履歴管理しないBUGLESSでは修正箇所がわかるように削除コメントは残していますが、Gitで履歴管理を行えるので、むしろ残っていると第３者から疑問に感じてしまいます。

2024-07-08 08:28 UTC, ma-miyagawa commented on study_template/web_application_2/src/view/BookApp.vue
> +  .wrap {
.wrapのスタイルも不要になったなら削除してください

2024-07-08 08:28 UTC, ma-miyagawa commented on study_template/web_application_2/package.json
> +    "serve": "vue-cli-service serve",
６、７行目の設定は、なぜ追加されたのでしょうか

2024-07-10 12:03 UTC, Itopan1108 commented
@esmtodoroki @esmtodoroki @ma-miyagawa 
指摘すべて修正し、対処することができました！
自信あり。
よろしくお願いします！　（デプロイやpushのコマンドは、忘れないよう悩みシートへ記載し管理します。）

2024-07-11 08:53 UTC, ma-miyagawa commented
@Itopan1108 

指摘に対して、修正されているのは確認できるのですが、
指摘されたことに対して、どう対応したのか、または質問に対しての回答を記載してから、再レビュー依頼をお願いします。
（横山さんの指摘分も含めて）

2024-07-12 10:41 UTC, ma-miyagawa commented
@Itopan1108 

指摘をおこなった箇所それぞれに、対応内容を記載してください
下記画像のReplyと書かれた部分のことです。
レビュー者はそれをみて指摘事項をCLOSEしています。

![image](https://github.com/user-attachments/assets/7c0ed898-3118-4e9e-8885-beb0ad179c66)

2024-07-14 03:15 UTC, esmtodoroki commented
@Itopan1108 
v-data-tableを使用したレスポンシブルデザインに改善されていることを確認しました。
あと1点、惜しいところがあります。細かいことですが表示項目に「ID」は要らないです。
仕様書には以下の記載があります。
**表示するデータは「タイトル」「ジャンル」「購入日」「購入者」のみとする**

2024-07-14 08:18 UTC, Itopan1108 commented
> @Itopan1108 v-data-tableを使用したレスポンシブルデザインに改善されていることを確認しました。 あと1点、惜しいところがあります。細かいことですが表示項目に「ID」は要らないです。 仕様書には以下の記載があります。 **表示するデータは「タイトル」「ジャンル」「購入日」「購入者」のみとする**

（返信）
ご指摘にそって、IDを取りました！表示されなくなったことを確認しました。
以下、リンク張ります。
https://script.google.com/a/macros/esm.co.jp/s/AKfycby6QUPSxrNtCRvGQM86wyi1VuZT3VXol99GDAnVsLMYY6Q0pdCY5RuIN2MNCp_ymDg/exec#/

ちなみに、仕様ですが、
『「タイトル」「ジャンル」「購入日」「購入者」のみ』とあるのは、５つのDB保有項目から「レビュー内容」は表示させないでね、という要件である
と受け取っていました。
最初に「機能としては以下を最低限保有」とあったので、そのほか、IDつけたり、機能を追加する分には、自由な部分なのかなーと。。そんな感じですー。

2024-07-15 03:11 UTC, ma-miyagawa requested changes
@Itopan1108 

これでみえるようななりましたでしょうか

2024-07-16 00:25 UTC, esmtodoroki commented
@Itopan1108 
表示項目の修正確認しました。
たしかに、伊藤さんが思ったように仕様書の記述からはそういう趣旨も受け取ることができる気がしますね。
私の思い違いだったら失礼しました。
レコードIDは今後書籍情報の修正や削除の機能を実装する際に必要になってくると思うので、うまく使ってください。

これで私の指摘はひとまず完了です。お疲れさまでした。LGTM🍨

2024-07-16 08:26 UTC, Itopan1108 reviewed
自己レビューを終わります。

2024-07-16 08:26 UTC, Itopan1108 commented on study_template/web_application_2/src/view/BookApp.vue
> +  <!--  <div class="wrap"> -->
なんか、削除（更新前）残したくなってしまいますね・・。
削除しました。

2024-07-16 08:26 UTC, Itopan1108 commented on study_template/web_application_2/src/view/BookApp.vue
> +  .wrap {
ご指摘通り不要になったため、削除しました。

2024-07-16 08:26 UTC, Itopan1108 commented on study_template/web_application_2/src/components/TheList.vue
> +<style scoped>
たしかに不要ですね。削除しました。

2024-07-16 08:26 UTC, Itopan1108 commented on study_template/web_application_2/package.json
> +    "serve": "vue-cli-service serve",
修正した記憶がありませんでした。
が、serve という単語で、わかりました。
以前、福井でのもくもく合宿でITS鈴木さんにサポートしていただいたとき、
毎回、npm run deploy のコマンドで、動作確認していたのを時間的に危惧していただき、
npm run serve のコマンドで確認できるようにして頂いたときの、対処いただいた部分です。

2024-07-16 08:26 UTC, Itopan1108 commented on study_template/web_application_2/public/index.html
> +      >
修正しました！差がでないよう、合わせました。

2024-07-16 08:26 UTC, Itopan1108 commented on study_template/web_application_2/src/App.vue
> +    <v-app-bar app dark color="primary">
修正しました！差がでないよう、合わせました。

2024-07-16 08:26 UTC, Itopan1108 commented on study_template/web_application_2/public/index.html
> +      >
テスト

2024-07-16 08:26 UTC, Itopan1108 commented on study_template/web_application_2/src/view/BookApp.vue
> +  .wrap {
> .wrapのスタイルも不要になったなら削除してください

ご指摘通り不要になったため、削除しました

2024-07-16 12:19 UTC, ma-miyagawa commented on study_template/web_application_2/src/components/TheList.vue
> +<style scoped>
削除されているのを確認しました。

2024-07-16 12:19 UTC, ma-miyagawa commented on study_template/web_application_2/src/view/BookApp.vue
> +  <!--  <div class="wrap"> -->
削除されているのを確認しました。

2024-07-16 12:19 UTC, ma-miyagawa commented on study_template/web_application_2/src/view/BookApp.vue
> +  .wrap {
削除されているのを確認しました。

2024-07-16 12:20 UTC, ma-miyagawa commented on study_template/web_application_2/package.json
> +    "serve": "vue-cli-service serve",
一時的に追加されていたと認識しました
削除されているのを確認しました。

2024-07-16 12:27 UTC, ma-miyagawa commented
@Itopan1108 

対応を確認しました。LGTM🙆

2024-07-17 05:30 UTC, h-yokoyama-eiwa commented on study_template/web_application_2/public/index.html
> +      >
修正されていることを確認しました。

2024-07-17 05:30 UTC, h-yokoyama-eiwa commented on study_template/web_application_2/src/App.vue
> +    <v-app-bar app dark color="primary">
修正されていることを確認しました。

2024-07-17 05:33 UTC, h-yokoyama-eiwa commented
@Itopan1108 
指摘箇所が修正されていることを確認できました。
LGTMです。

2024-07-17 14:07 UTC, Itopan1108 commented
ありがとうございます。
たくさん、指摘いただきました。
ようやく、クローズできます！

2024-07-17 14:10 UTC, merged